"use client";
import {useState} from "react";
import MainStringInput from "@/components/MainStringInput";
import HoverDiv from "@/components/HoverDiv";
import {FaBroom, FaCode} from "react-icons/fa6";
const languages=["JavaScript","CSS","HTML/XML","JSON","SQL"] as const;
export default function CodeFormatterClient(){const [language,setLanguage]=useState<(typeof languages)[number]>("JavaScript");const [input,setInput]=useState("");const [output,setOutput]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");const format=()=>{setLoading(true);setError("");setTimeout(()=>{try{setOutput(formatCode(input,language))}catch(reason){setError(reason instanceof Error?reason.message:"Formatting failed")}finally{setLoading(false)}},40)};return <div className="mx-auto max-w-6xl pb-16"><header className="mb-5"><div className="flex items-center gap-3"><FaCode className="text-xl text-cyan-400"/><h1 className="text-2xl font-bold">Code formatter</h1></div><p className="mt-1 text-sm text-zinc-500">Clean up common code and data formats locally in your browser.</p></header><div className="mb-3 flex flex-wrap items-end gap-3"><label className="text-[10px] uppercase tracking-wider text-zinc-500">Language<select value={language} onChange={e=>setLanguage(e.target.value as typeof language)} className="mt-1 block rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2 text-sm text-white">{languages.map(item=><option key={item}>{item}</option>)}</select></label><HoverDiv type="SAVE" icon={<FaBroom/>} onClick={format} disabled={!input||loading} className="px-4 py-2 text-sm">Format code</HoverDiv></div>{loading&&<div className="mb-3 h-10 animate-pulse rounded-lg bg-zinc-900"/>}<div className="grid gap-4 lg:grid-cols-2"><Editor label="Unformatted" value={input} onChange={setInput}/><Editor label="Formatted" value={output} onChange={setOutput}/></div>{error&&<p className="mt-3 text-xs text-red-400">{error}</p>}</div>}
function Editor({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <div><label className="mb-2 block text-[10px] uppercase tracking-wider text-zinc-500">{label}</label><MainStringInput multiline rows={22} value={value} onChange={onChange} className="border-zinc-800 bg-black/20" inputClassName="font-mono text-xs leading-5"/></div>}
function formatCode(input:string,language:string){if(language==="JSON")return JSON.stringify(JSON.parse(input),null,2);if(language==="SQL")return input.replace(/\s+/g," ").replace(/\b(SELECT|FROM|WHERE|JOIN|LEFT JOIN|RIGHT JOIN|INNER JOIN|GROUP BY|ORDER BY|HAVING|LIMIT|INSERT INTO|VALUES|UPDATE|SET|DELETE FROM|AND|OR)\b/gi,"\n$1").trim();if(language==="HTML/XML")return formatMarkup(input);return braceFormat(input)}
function braceFormat(input:string){let depth=0;return input.replace(/\s+/g," ").replace(/\s*([{};])\s*/g,"$1\n").split("\n").filter(Boolean).map(line=>{if(line.startsWith("}"))depth=Math.max(0,depth-1);const result="  ".repeat(depth)+line.trim();if(line.endsWith("{"))depth++;return result}).join("\n")}
function formatMarkup(input:string){let depth=0;return input.replace(/>\s*</g,"><").split(/(?=<)|(?<=>)/).filter(value=>value.trim()).map(value=>{const item=value.trim();if(/^<\//.test(item))depth=Math.max(0,depth-1);const result="  ".repeat(depth)+item;if(/^<[^!?/][^>]*[^/]?>$/.test(item)&&!/<\/(?:[^>]+)>$/.test(item))depth++;return result}).join("\n")}
