"use client";
import {useState} from "react";
import MainStringInput from "@/components/MainStringInput";
import HoverDiv from "@/components/HoverDiv";
import {FaBroom, FaCode, FaCompress} from "react-icons/fa6";
export default function JsonWorkbenchClient() { const [input,setInput]=useState(""); const [output,setOutput]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const run=(mode:"format"|"minify"|"sort")=>{setLoading(true);setError("");setTimeout(()=>{try{const parsed=JSON.parse(input);const value=mode==="sort"?sortObject(parsed):parsed;setOutput(JSON.stringify(value,null,mode==="minify"?0:2));}catch(reason){setError(reason instanceof Error?reason.message:"Invalid JSON");setOutput("");}finally{setLoading(false);}},30)}; return <Shell title="JSON workbench" subtitle="Validate, format, minify, and recursively sort JSON." icon={<FaCode/>}>{loading&&<Ghost/>}<div className="grid gap-4 lg:grid-cols-2"><Editor label="Input" value={input} onChange={setInput}/><Editor label="Output" value={output} onChange={setOutput}/></div><div className="mt-3 flex flex-wrap gap-2"><HoverDiv type="INFO" icon={<FaBroom/>} onClick={()=>run("format")} disabled={!input||loading} className="px-4 py-2 text-sm">Format</HoverDiv><HoverDiv type="INFO" icon={<FaCompress/>} onClick={()=>run("minify")} disabled={!input||loading} className="px-4 py-2 text-sm">Minify</HoverDiv><HoverDiv type="SAVE" icon={<FaCode/>} onClick={()=>run("sort")} disabled={!input||loading} className="px-4 py-2 text-sm">Sort keys</HoverDiv></div>{error&&<p className="mt-3 text-xs text-red-400">{error}</p>}</Shell>; }
function sortObject(value: unknown): unknown { if(Array.isArray(value))return value.map(sortObject); if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,sortObject(item)])); return value; }
function Editor({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <section><label className="mb-2 block text-[10px] uppercase tracking-wider text-zinc-500">{label}</label><MainStringInput multiline rows={20} value={value} onChange={onChange} placeholder={label === "Input" ? "Paste JSON here…" : "Formatted JSON appears here…"} className="border-zinc-800 bg-zinc-950" inputClassName="font-mono text-xs leading-5"/></section>}
function Shell({title,subtitle,icon,children}:{title:string;subtitle:string;icon:React.ReactNode;children:React.ReactNode}){return <div className="mx-auto max-w-6xl pb-16"><header className="mb-5"><div className="flex items-center gap-3 text-amber-400"><span className="text-xl">{icon}</span><h1 className="text-2xl font-bold text-white">{title}</h1></div><p className="mt-1 text-sm text-zinc-500">{subtitle}</p></header>{children}</div>}
function Ghost(){return <div className="mb-3 grid animate-pulse grid-cols-2 gap-4"><div className="h-8 rounded bg-zinc-900"/><div className="h-8 rounded bg-zinc-900"/></div>}
