"use client";
import {useState} from "react";
import MainStringInput from "@/components/MainStringInput";
import HoverDiv from "@/components/HoverDiv";
import {FaCheck,FaCopy,FaFingerprint} from "react-icons/fa6";
type Hashes={sha256:string;sha384:string;sha512:string;crc32:string};
export default function FileChecksumClient(){const [file,setFile]=useState<File|null>(null);const [hashes,setHashes]=useState<Hashes|null>(null);const [expected,setExpected]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");const calculate=async(selected?:File)=>{const target=selected||file;if(!target)return;if(target.size>100*1024*1024){setError("File limit is 100 MB.");return}setFile(target);setHashes(null);setLoading(true);setError("");try{const data=await target.arrayBuffer();const [a,b,c]=await Promise.all([crypto.subtle.digest("SHA-256",data),crypto.subtle.digest("SHA-384",data),crypto.subtle.digest("SHA-512",data)]);setHashes({sha256:hex(a),sha384:hex(b),sha512:hex(c),crc32:crc(new Uint8Array(data))})}catch{setError("Could not calculate checksums.")}finally{setLoading(false)}};const matched=expected.trim()&&hashes?Object.values(hashes).some(value=>value.toLowerCase()===expected.trim().toLowerCase()):false;return <div className="mx-auto max-w-4xl pb-16"><header className="mb-5"><div className="flex items-center gap-3"><FaFingerprint className="text-xl text-pink-400"/><h1 className="text-2xl font-bold">File checksum</h1></div><p className="mt-1 text-sm text-zinc-500">Calculate hashes locally. Your file is never uploaded.</p></header><label className="box-primary block cursor-pointer rounded-xl border-dashed p-8 text-center text-sm text-zinc-500"><input type="file" className="hidden" onChange={event=>void calculate(event.target.files?.[0])}/>{file?`${file.name} · ${formatSize(file.size)}`:"Drop or choose a file up to 100 MB"}</label>{loading&&<div className="mt-4 space-y-3 animate-pulse">{[1,2,3,4].map(item=><div key={item} className="h-16 rounded-xl bg-zinc-900"/>)}</div>}{hashes&&<div className="mt-4 space-y-3">{Object.entries(hashes).map(([name,value])=><div key={name} className="box-primary rounded-xl p-4"><div className="mb-1 text-[10px] uppercase tracking-wider text-zinc-500">{name}</div><div className="flex items-center gap-2"><code className="min-w-0 flex-1 break-all text-xs text-zinc-300">{value}</code><HoverDiv type="INFO" icon={<FaCopy/>} onClick={()=>void navigator.clipboard.writeText(value)} className="shrink-0 p-2"/></div></div>)}<div className="pt-2"><label className="mb-1 block text-[10px] uppercase tracking-wider text-zinc-500">Compare expected checksum</label><MainStringInput value={expected} onChange={setExpected} placeholder="Paste a checksum" className="border-zinc-800 bg-black/20" inputClassName="font-mono text-xs"/>{expected&&<p className={`mt-2 flex items-center gap-2 text-xs ${matched?"text-emerald-400":"text-red-400"}`}><FaCheck/>{matched?"Checksum matches":"No calculated checksum matches"}</p>}</div></div>}{error&&<p className="mt-3 text-xs text-red-400">{error}</p>}</div>}
function hex(value:ArrayBuffer){return Array.from(new Uint8Array(value),byte=>byte.toString(16).padStart(2,"0")).join("")}
function crc(bytes:Uint8Array){let value=0xffffffff;for(const byte of bytes){value^=byte;for(let i=0;i<8;i++)value=(value>>>1)^((value&1)?0xedb88320:0)}return ((value^0xffffffff)>>>0).toString(16).padStart(8,"0")}
function formatSize(bytes:number){return bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`}
