"use client";
import {useState} from "react";
import MainStringInput from "@/components/MainStringInput";
import HoverDiv from "@/components/HoverDiv";
import {useUser} from "@/hooks/useUser";
import {getApiUrl} from "@/lib/core";
import {FaArrowRotateRight, FaGlobe, FaMagnifyingGlass} from "react-icons/fa6";

type Registration = {handle?: string; registrar?: string; registrant?: string; registrantOrganization?: string; registrantAddress?: string; registrantHandle?: string; registeredAt?: string; expiresAt?: string; updatedAt?: string; statuses: string[]; nameservers: string[]};
type DnsResult = {domain: string; records: Record<string, string[]>; registration?: Registration};

export default function DnsLookupClient() {
    const {user} = useUser(); const [domain, setDomain] = useState(""); const [result, setResult] = useState<DnsResult | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
    const lookup = async () => { if (!domain.trim() || !user?.apiKey || loading) return; setLoading(true); setError(""); setResult(null); try { const response = await fetch(`${getApiUrl()}/v1/tools/network/dns?domain=${encodeURIComponent(domain.trim())}`, {cache: "no-store", credentials: "include", headers: {"X-API-Key": user.apiKey, "Cache-Control": "no-cache"}}); const data = await response.json(); if (!response.ok) throw new Error(data?.message || "DNS lookup failed"); setResult(data); } catch (reason) { setError(reason instanceof Error ? reason.message : "DNS lookup failed"); } finally { setLoading(false); } };
    return <div className="mx-auto max-w-6xl pb-16 xl:pb-0"><header className="mb-5"><div className="flex items-center gap-3"><FaGlobe className="text-xl text-blue-400"/><h1 className="text-2xl font-bold text-white">DNS & domain lookup</h1></div><p className="mt-1 text-sm text-zinc-500">View live DNS records and public RDAP registration information without Space caching the result.</p></header><div className="box-primary rounded-xl p-4 sm:p-5"><label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-wider text-zinc-500">Domain</label><div className="flex flex-col gap-2 sm:flex-row"><MainStringInput type="text" value={domain} onChange={setDomain} onKeyDown={event => {if (event.key === "Enter") void lookup();}} placeholder="example.com" className="min-w-0 flex-1 rounded-lg border-zinc-800 bg-black/25" inputClassName="py-2.5 font-mono text-sm"/><HoverDiv type="INFO" icon={loading ? <FaArrowRotateRight className="animate-spin"/> : <FaMagnifyingGlass/>} onClick={lookup} disabled={!domain.trim() || loading} className="px-5 py-2.5 text-sm font-semibold">{loading ? "Looking up…" : "Lookup"}</HoverDiv></div></div>{error && <div className="mt-3 rounded-xl border border-red-900/60 bg-red-950/30 p-4 text-sm text-red-300">{error}</div>}{result && <div className="mt-4 grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-3">{Object.entries(result.records).map(([type, values]) => <RecordList key={type} label={type} values={values}/>)}</div><RegistrationCard value={result.registration}/></div>}</div>;
}
function RecordList({label, values}: {label: string; values: string[]}) { return <section className="box-primary overflow-hidden rounded-xl"><div className="flex items-center justify-between border-b border-zinc-800 px-4 py-2"><span className="text-[10px] font-semibold uppercase tracking-wider text-zinc-500">{label}</span><span className="font-mono text-[9px] text-zinc-700">{values.length}</span></div>{values.length ? <div className="divide-y divide-zinc-800">{values.map((value, index) => <div key={`${value}-${index}`} className="break-all px-4 py-3 font-mono text-xs leading-5 text-zinc-300">{value}</div>)}</div> : <p className="px-4 py-3 text-xs text-zinc-700">No records</p>}</section>; }
function RegistrationCard({value}: {value?: Registration}) { return <aside className="box-primary rounded-xl p-4 lg:sticky lg:top-0"><h2 className="mb-3 text-sm font-semibold text-white">Registration data</h2>{value ? <dl className="space-y-3 text-xs"><Info label="Registrant" value={value.registrant}/><Info label="Organization" value={value.registrantOrganization}/><Info label="Public address" value={value.registrantAddress}/><Info label="Contact handle" value={value.registrantHandle}/><Info label="Registrar" value={value.registrar}/><Info label="Registry ID" value={value.handle}/><Info label="Registered" value={formatDate(value.registeredAt)}/><Info label="Expires" value={formatDate(value.expiresAt)}/><Info label="Updated" value={formatDate(value.updatedAt)}/><Info label="Status" value={value.statuses?.join(", ")}/><Info label="RDAP nameservers" value={value.nameservers?.join("\n")}/></dl> : <p className="text-xs leading-5 text-zinc-600">No public RDAP registration data was returned. Registrant details are often privacy-redacted.</p>}</aside>; }
function Info({label, value}: {label: string; value?: string}) { return <div><dt className="mb-1 text-[9px] uppercase tracking-wider text-zinc-600">{label}</dt><dd className="whitespace-pre-line break-all font-mono text-zinc-300">{value || "Not publicly available"}</dd></div>; }
function formatDate(value?: string) { return value ? new Date(value).toLocaleString() : undefined; }
